apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: Kafka Connect and Stream Monitoring
spec:
  schedule: "*/20 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: Kafka Connect Monitoring
            image: docker-registry:5000/kafka_monitoring_tst:1.0.1
          restartPolicy: Never
